### ISSUE TITLE
Unable to setup Kubectl command in DCOS Master

### ISSUE THREAD

**Issue by arnabnandy1706** [mesosphere/dcos-kubernetes-quickstart#105]
Hello,

I am running below the command to get kubectl in master node but getting below the error.

Command:
        `dcos kubernetes kubeconfig --apiserver-url https://<public-slave-agent-ip>:6443 --insecure-skip-tls-verify`

ERROR:
`
2018/10/10 14:12:40 failed to update kubeconfig context '10211203926443': HTTP GET Query for http://<master-ip>/service/kubernetes/v1/auth/data failed: 403 Forbidden
Response: the service account secret cannot be served over an insecure connection
Response data (71 bytes): the service account secret cannot be served over an insecure connection
HTTP query failed
`
Please help me.

Regards,
Arnab

**Comment by arnabnandy1706** [comment]
@hectorj2f Please help me !!!

**Comment by bmcstdio** [comment]
@arnabnandy1706 as mentioned in the [documentation](https://docs.mesosphere.com/services/kubernetes/1.3.0-1.10.8/connecting-clients/#connecting-clients), you must make sure that `dcos` (the DC/OS CLI) is configured to access the target cluster using HTTPS:

>  dcos MUST be configured to access the desired DC/OS cluster over HTTPS before proceeding. One must make sure that
>
> `$ dcos config show core.dcos_url`
>
> returns a URL that starts with https:// and. In case the returned URL doesn't start with https://, one must run
>
> `$ dcos config set core.dcos_url https://<master-ip>`
>
> In case the TLS certificate used by DC/OS is not trusted one additionally needs to run the following command to disable TLS verification:
>
> `$ dcos config set core.ssl_verify false`

Could you please make this change and try again?

**Comment by arnabnandy1706** [comment]
Hello @bmcstdio ,

Thanks for the help.

This is working fine for me now.

Warm Regards,
Arnab

**Comment by arnabnandy1706** [comment]
@bmcstdio 

It got register to access Kubernetes Cluster API.

`kubeconfig context '10211203926443' updated successfully`

But how to access the kubernetes kubectl command from the master node?

Warm Regards,
Arnab

**Comment by pires** [comment]
You can setup `kubectl` on any node, internal to DC/OS or not, by following [our instructions](https://docs.mesosphere.com/services/kubernetes/1.3.0-1.10.8/connecting-clients/#connecting-clients).

We do not support specific scenarios such as configuring `kubectl` in a DC/OS master, and we actually advise you not to do it, for security reasons.
