### ISSUE TITLE
Unable to delpoy Application on Kubernetes running on DCOS

### ISSUE THREAD

**Issue by arnabnandy1706** [mesosphere/dcos-kubernetes-quickstart#108]
Hello All,

I am deploying on Application on top of Kubernetes Cluster which is running on top of DC/OS Cluster.

But when I am executing below the command:

`# kubectl create -f deploy.yaml`

The container is not getting created and below the error I can see in describe command output.: 

`Events:`
 ` Type     Reason            Age                    From               Message`
`  ----     ------            ----                   ----               -------`
`  Warning  FailedScheduling  4m41s (x156 over 49m)  default-scheduler  0/3 nodes are available: 3 node(s) had taints that the pod didn't tolerate.`

Please let me know in case you need any further information.

Thanks in advance.

Regards,
Arnab

**Comment by arnabnandy1706** [comment]
Taint of Kubernetes Nodes:

`# kubectl describe nodes <Node_Name>`

Output:
`Taints:             kubelet-resource-watchdog.kubernetes.dcos.io/public=NodeDiskPressure:NoSchedule`

I am not sure whether this should be <None>.

Please suggest.

Regards,
Arnab

**Comment by arnabnandy1706** [comment]
@pires

**Comment by arnabnandy1706** [comment]
Any help on this please ?

**Comment by pires** [comment]
Closed due to inactivity.

**Comment by nadendlaprasad** [comment]
I am facing the same issue and I have cleaned up disk space but still couldn't get rid of taints and unable to deploy. If i check node details i can see nodiskpressure status set to false and taint still there.

Anything else i should do ?
