### ISSUE TITLE
How to access kubernetes service from outside Mesos?

### ISSUE THREAD

**Issue by nitrogear** [mesosphere/dcos-kubernetes-quickstart#15]
I installed kubernetes on top of Mesos on AWS using Cloudformation. Installed dashboard and was able to open UI using ssh port forwarding.
However I want to open dashboard from outside Mesos - how I can do it?
I don't understand how to expose port of kubernetes service with Mesos.

**Comment by nitrogear** [comment]
Used externalIPs to expose service to specific node:
https://kubernetes.io/docs/concepts/services-networking/service/#external-ips

**Comment by pires** [comment]
@nitrogear would be great if you could open a PR with instructions on how you achieved this ;)
