### ISSUE TITLE
[FIXED] Can't create Kubernetes nodes

### ISSUE THREAD

**Issue by nitrogear** [mesosphere/dcos-kubernetes-quickstart#17]
I'm trying to install beta-kubernetes on DC/OS 1.10.0 using GUI (Services->Run a Service->Install a Package). I changed default parameters:
Kubelet MEMORY SIZE -> 8192
Kubernetes NODE COUNT -> 5
After service is deployed I see only 7 active tasks and there is no any node
```
#kubectl get namespaces
NAME          STATUS    AGE
default       Active    1d
kube-public   Active    1d
kube-system   Active    1d

#kubectl get nodes
No resources found.
```
We run DC/OS on AWS 7 instances m3.xlarge. Our current usage is 8 of 28 Shares for CPU and 9 GiB of 96 GiB, so lack of resources shouldn't be an issue.

**Comment by pires** [comment]
Can you try [the new release](https://docs.mesosphere.com/service-docs/beta-kubernetes/0.2.0-1.7.6-beta) and report back?

**Comment by rimusz** [comment]
seeing same with new release

**Comment by pires** [comment]
@rimusz you only see 7 tasks too?

**Comment by rimusz** [comment]
I see these tasks:
```
3 etcd
3 kube-api
3 kube-controller
3 kube-scheduler
1 kubernetes
```

**Comment by rimusz** [comment]
ok, my issue was I had downsized GCE nodes as `n1-standard-4`
creating `options.json`:
```
{ "kubernetes":
    {
      "node_count": 3,
      "node_cpus": 0.5,
      "node_mem": 512,
      "node_disk": 512
    }
}
```
and running `dcos package install --yes beta-kubernetes --options options.json` I got k8s cluster running. 
Thanks to @pires for the help.

**Comment by pires** [comment]
@nitrogear issue was also the lack of resources.

While a cluster may have more than enough resources available to it, the fact is that right now we can only run one Kubernetes node per DC/OS agent and we need the agent to have enough resources available, i.e. not allocated to other DC/OS tasks.

This [limitation is identified](https://docs.mesosphere.com/service-docs/beta-kubernetes/0.2.0-1.7.6-beta/limitations/) and we are working to be able to run multiple Kubernetes nodes on the same DC/OS agent.
