### ISSUE TITLE
Warning about DC/OS nodes requirement 

### ISSUE THREAD

**Issue by rimusz** [mesosphere/dcos-kubernetes-quickstart#19]
read me should have a warning about 6 monsters nodes will be created.
got puzzled for a while as docker deploy failed with missing VMs, then double checked that GCS compute instance group was trying to created 6 instances, my account needed quote increase.

**Comment by hectorj2f** [comment]
👋 @rimusz Thanks for reporting this issue! Yeah, we probably need to add some additional links to these sentence in the README `Google Cloud (GCE) credentials (AWS and Azure are supported as well) with the necessary permissions`

**Comment by rimusz** [comment]
maybe also to have an option to set lover spec VMs, as current ones are very beefy ones.

**Comment by pires** [comment]
@spahl @smugcloud I think that we should remove the automation (Makefile) if we can't support it. At this time, I don't think we can and it seems to be causing a negative impact.

**Comment by hectorj2f** [comment]
@pires @spahl We could easily improve this user experience by extracting the yaml files with the vm definitions out of the Makefile. 

A quick solution could be to move the yaml templates out of the Makefile and simply refer them in the Makefile by `LAUNCH_CONFIG_GCE=`cat $(./resources/gce.template.yaml)`. With this solution, it'd be more clear to users to see which target infrastructure we support, as well as to facilitate its customization. I can send a PR if you agree about it.

**Comment by hectorj2f** [comment]
We've extracted the yaml files out of the Makefile into the `resources` directory (https://github.com/mesosphere/dcos-kubernetes-quickstart/tree/master/resources). We also added a note in the README.md to allow users to customize them.

I think we can close this issue.

**Comment by rimusz** [comment]
cool
