### ISSUE TITLE
[FIXED] kubectl-tunnel cannot bind: Cannot assign requested address

### ISSUE THREAD

**Issue by rimusz** [mesosphere/dcos-kubernetes-quickstart#20]
```
make kubectl-tunnel
ssh -i .id_key -f -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" -o "ServerAliveInterval=120" \
	 -N -L 9000:apiserver-insecure.kubernetes.l4lb.thisdcos.directory:9000 \
	core@1.2.3.4
Warning: Permanently added '1.2.3.4' (ECDSA) to the list of known hosts.
bind: Cannot assign requested address
channel_setup_fwd_listener_tcpip: cannot listen to port: 9000
Could not request local forwarding.
```

**Comment by pires** [comment]
Is your host TCP 9000 already bound?

**Comment by rimusz** [comment]
nope, as that was running commands for the docker container

**Comment by pires** [comment]
There's definitely [a problem with forwarding](https://help.ubuntu.com/community/SSH/OpenSSH/PortForwarding#Troubleshooting):
> bind: Address already in use channel_setup_fwd_listener: cannot listen to port: <port number> Could not request local forwarding. then someone is already listening on that port number. You won't be able to listen on that port until the other person has finished with it.

**Comment by rimusz** [comment]
already destroyed the cluster, might give it a go tomorrow

**Comment by hectorj2f** [comment]
@rimusz @pires  You get that error if you try to setup the tunnel when you already did it before.

**Comment by rimusz** [comment]
ok, fetched the first error:
```
 make kubectl-tunnel
cat cluster_info.json | jq '{ssh_private_key} | .ssh_private_key' | sed 's/\\n/\n/g' | sed 's/"//g' > .id_key
chmod 400 .id_key
ssh -i .id_key -f -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" -o "ServerAliveInterval=120" \
	 -N -L 9000:apiserver-insecure.kubernetes.l4lb.thisdcos.directory:9000 \
	core@1.2.3.4
Warning: Permanently added '1.2.3.4' (ECDSA) to the list of known hosts.
bind: Cannot assign requested address
```

**Comment by pires** [comment]
Ah, do you have IPv6 enabled on your machine?

**Comment by rimusz** [comment]
on my Mac I have IPv6 as `Link-local only` set

**Comment by pires** [comment]
Can you edit your `Makefile` and add `-4` flag to the ssh command, i.e. `ssh -i .id_key -4 -f -o (...)` and try again?

**Comment by rimusz** [comment]
`-4` (IPv4) did the trick

**Comment by pires** [comment]
Cool! We are working on a bug-fix release that will update the public docs and include this. I'll close when it's released.

**Comment by pires** [comment]
The [0.2.1-1.7.7-beta release](https://docs.mesosphere.com/service-docs/beta-kubernetes/0.2.1-1.7.7-beta/release-notes/) already provides updated documentation. Will still need to fix this repo. Will do it tomorrow.

**Comment by pires** [comment]
Fixed in https://github.com/mesosphere/dcos-kubernetes-quickstart/commit/ec5ba644a2fbd6fc7c8eb3a4beb4f55dd4edd622.
