### ISSUE TITLE
mandatory-addons-0 failed

### ISSUE THREAD

**Issue by ezreal92170** [mesosphere/dcos-kubernetes-quickstart#27]
I tried to install the default config of the dcos beta-kubernetes package v 0.2.2-1.7.7-beta.
The first 19 tasks are healthy but the mandatory-addons-0 failed with the following error
Any idea?

`2017/10/14 21:47:28 No $MESOS_SANDBOX/.ssl directory found. Cannot install certificate. Error: stat /var/lib/mesos/slave/slaves/2153cc40-c292-4ee6-a7d9-9771aacd2109-S0/frameworks/dd0f75fe-9b95-4a2d-a514-56ab403fb7bf-0001/executors/mandatory-addons__ae8a9ee7-a3fa-4e8d-88ce-c4edcff236a9/runs/5ce2fe35-496c-4ba6-9032-87f7a05a5bff/containers/c79ed785-29d7-41e9-8b5d-d9e351e05c82/.ssl: no such file or directory
2017/10/14 21:47:28 Local IP --> 10.90.140.54
2017/10/14 21:47:28 SDK Bootstrap successful.

 ######  Deploying kube-dns components --  ###### 
configmap "kube-dns" configured
service "kube-dns" configured
deployment "kube-dns" configured
kube-dns check failed and is not ready`

**Comment by hectorj2f** [comment]
@ezreal92170 I just installed `beta-kubernetes` package `v0.2.2-1.7.7-beta` without any problem. However it is possible `kube-dns` isn't ready whenever we try to deploy it in the first iteration getting this error `kube-dns check failed and is not ready`. The system creates a new task `mandatory-addons-0-kube-dns` that retries to install `kube-dns` again. Can you confirm you don't see any `mandatory-addons-0-kube-dns` task with `Finished` status ? If so, could you run `$ kubectl get pods -n kube-system` to give us more details ?

**Comment by ezreal92170** [comment]
Yes I don't see any `mandatory-addons-0-kube-dns` task with `Finished` status..

kubectl get pods -n kube-system
NAME                        READY     STATUS              RESTARTS   AGE
kube-dns-2102953216-dvw4g   0/3       ContainerCreating   0          <invalid>
`
And I have the following error log on kube node  :

E1015 19:27:04.550963      53 remote_runtime.go:91] RunPodSandbox from runtime service failed: rpc error: code = 2 desc = failed pulling image "gcr.io/google_containers/pause-amd64:3.0": Error response from daemon: {"message":"Get https://gcr.io/v1/_ping: dial tcp 173.194.208.82:443: i/o timeout"}
E1015 19:27:04.551042      53 kuberuntime_sandbox.go:54] CreatePodSandbox for pod "kube-dns-2102953216-dvw4g_kube-system(66e22e9c-b1cd-11e7-9aac-801844e90be0)" failed: rpc error: code = 2 desc = failed pulling image "gcr.io/google_containers/pause-amd64:3.0": Error response from daemon: {"message":"Get https://gcr.io/v1/_ping: dial tcp 173.194.208.82:443: i/o timeout"}

I need to use http proxy to access Internet. My issue on this subject was closed but maybe it's still an issue.

**Comment by hectorj2f** [comment]
@ezreal92170 yeah, it seems it cannot pull the image. That is why it doesn't work.

**Comment by pires** [comment]
@ezreal92170 are you behind a proxy?

@spahl aren't we supposed to be air-gap friendly?

**Comment by spahl** [comment]
If you are behind a proxy or do not have direct internet access from the nodes then you need to build a local universe containing the beta-kubernetes package and use that.

More here: https://dcos.io/docs/1.10/administering-clusters/deploying-a-local-dcos-universe/#-a-name-build-a-installing-your-own-set-of-universe-packages

**Comment by ezreal92170** [comment]
I am behind a proxy but I don't understand why building a local universe could help.
I have no problem to create the framework.

**Comment by pires** [comment]
The problem seems to be that the framework scheduler can't download the artifacts it needs, namely the official Kubernetes components, because it doesn't know about your proxy settings. This is why we have what @spahl linked above.

**Comment by pires** [comment]
Should be fixed in 0.3.0-1.7.10-beta release, for as long as you have DC/OS configured to use the HTTP proxy.

**Comment by deric** [comment]
I'm having the same issue with `0.4.0-1.9.0-beta`. All artifacts seems to be downloaded in the work dir.
```
2018/01/11 10:58:59 Resolve disabled via -resolve=false: Skipping host resolution
2018/01/11 10:58:59 Template handling disabled via -template=false: Skipping any config templates
2018/01/11 10:58:59 No $MESOS_SANDBOX/.ssl directory found. Cannot install certificate. Error: stat /var/lib/mesos/slave/slaves/59336e89-bac9-44c0-ba44-78a66392b7b1-S8/frameworks/56308059-3e74-48f4-86a9-67f9bd519f44-0001/executors/dev_k8.69908f7c-f6be-11e7-8ff9-fe0d65b1eb4a/runs/82acd8eb-26f1-47c8-9dce-b72d3cfbb954/.ssl: no such file or directory
2018/01/11 10:58:59 Local IP --> 192.168.5.91
2018/01/11 10:58:59 SDK Bootstrap successful.
Exception in thread "main" com.mesosphere.sdk.kubernetes.scheduler.tls.exceptions.UnrecoverableTLSException: com.mesosphere.sdk.state.StateStoreException: Key cannot contain '/' (reason: LOGIC_ERROR)
	at com.mesosphere.sdk.kubernetes.scheduler.tls.StateStoreTLSStore.loadServiceAccountKeyPair(StateStoreTLSStore.java:69)
	at com.mesosphere.sdk.kubernetes.scheduler.tls.OpenTLSProvisioner.initializeServiceAccountKeyPair(OpenTLSProvisioner.java:64)
	at com.mesosphere.sdk.kubernetes.scheduler.tls.TLSProvisioner.initialize(TLSProvisioner.java:63)
	at com.mesosphere.sdk.kubernetes.scheduler.Main.main(Main.java:61)
Caused by: com.mesosphere.sdk.state.StateStoreException: Key cannot contain '/' (reason: LOGIC_ERROR)
	at com.mesosphere.sdk.state.StateStore.validateKey(StateStore.java:582)
	at com.mesosphere.sdk.state.StateStore.fetchProperty(StateStore.java:387)
	at com.mesosphere.sdk.kubernetes.scheduler.tls.StateStoreTLSStore.loadServiceAccountKeyPair(StateStoreTLSStore.java:60)
	... 3 more
I0111 10:59:21.747092    11 executor.cpp:925] Command exited with status 1 (pid: 15)
I0111 10:59:22.748448    14 process.cpp:1072] Failed to accept socket: future discarded
```

**Comment by pires** [comment]
@ezreal92170 https://docs.mesosphere.com/services/beta-kubernetes/0.4.0-1.9.0-beta/advanced-install/#when-you-have-a-proxy

**Comment by pires** [comment]
@deric that's a different issue and i'll open a new one with your feedback.

**Comment by cap1981** [comment]
@pires was new issue created for @deric 's  issue? 
thanks!

**Comment by pires** [comment]
@cap1981 https://github.com/mesosphere/dcos-kubernetes-quickstart/issues/52

We are about to release a new beta that includes a lot of bug-fixes. Stay tuned.

**Comment by cap1981** [comment]
Thank you! i am dealing with similar issues with mandatroy-addon.
