### ISSUE TITLE
Can't uninstall kubernetes service

### ISSUE THREAD

**Issue by nitrogear** [mesosphere/dcos-kubernetes-quickstart#28]
We had k8s service with 5 nodes (21 running tasks) on DC/OC 1.10. I noticed that some tasks failed and today only 8 tasks were running. I tried to uninstall service by:
```
> dcos package uninstall beta-kubernetes --app-id=/kubernetes
WARNING: This action cannot be undone. This will uninstall [/kubernetes] and delete all of its persistent (logs, configurations, database artifacts, everything).
Please type the name of the service to confirm: /kubernetes
Uninstalled package [beta-kubernetes] version [0.2.1-1.7.7-beta]
DC/OS Kubernetes has been uninstalled.
```

However, service wasn't completely removed and now I see only 1 task kubernetes.565e588c-b318-11e7-963f-46f4cd883ac6 in unhealthy state. Tried to run uninstall command again, but it didn't help.
How I can delete the service?

**Comment by hectorj2f** [comment]
@nitrogear Can you try the following command `dcos marathon app remove /kubernetes` ? If that doesn't work, try to use the janitor https://dcos.io/docs/1.7/usage/managing-services/uninstall/. This issues isn't related to the kubernetes package.

**Comment by nitrogear** [comment]
It helped! Thank you very much
