### ISSUE TITLE
Can't uninstall

### ISSUE THREAD

**Issue by nitrogear** [mesosphere/dcos-kubernetes-quickstart#29]
Kubernetes service keeps crashing when I provision it from UI or from dcos console.
I see only one task running (name is changing):
```
kubernetes.fcf88214-b366-11e7-963f-46f4cd883ac6
```
and a 200+ completed tasks (failed/killed).
Trying to install beta-kubernetes 0.2.2-1.7.7-beta on DC/OS 1.10.
I tried to deleted kubernetes, uninstall command said that it's removed, but I see that kubernetes service is still exist. The only way to remove it is:
```
dcos marathon app remove /kubernetes
```

**Comment by adam-carbone** [comment]
I1018 02:36:02.568322  4305 fetcher.cpp:533] Fetcher Info: {"cache_directory":"\/tmp\/mesos\/fetch\/root","items":[{"action":"BYPASS_CACHE","uri":{"cache":false,"executable":false,"extract":true,"value":"https:\/\/downloads.mesosphere.com\/java\/jre-8u144-linux-x64.tar.gz"}},{"action":"BYPASS_CACHE","uri":{"cache":false,"executable":false,"extract":true,"value":"https:\/\/downloads.mesosphere.com\/kubernetes\/assets\/0.2.2-1.7.7-beta\/kubernetes-scheduler.zip"}},{"action":"BYPASS_CACHE","uri":{"cache":false,"executable":false,"extract":true,"value":"https:\/\/downloads.mesosphere.io\/libmesos-bundle\/libmesos-bundle-1.10-1.4-63e0814.tar.gz"}}],"sandbox_directory":"\/var\/lib\/mesos\/slave\/slaves\/ad94e382-26c1-4832-bbff-b08e21a835d6-S8\/frameworks\/ad94e382-26c1-4832-bbff-b08e21a835d6-0001\/executors\/kubernetes.151a7920-b3ad-11e7-963f-46f4cd883ac6\/runs\/c581bf73-06f9-4fec-9841-c2f798ede98e","user":"root"}
I1018 02:36:02.572930  4305 fetcher.cpp:444] Fetching URI 'https://downloads.mesosphere.com/java/jre-8u144-linux-x64.tar.gz'
I1018 02:36:02.572954  4305 fetcher.cpp:285] Fetching directly into the sandbox directory
I1018 02:36:02.572989  4305 fetcher.cpp:222] Fetching URI 'https://downloads.mesosphere.com/java/jre-8u144-linux-x64.tar.gz'
I1018 02:36:02.573024  4305 fetcher.cpp:165] Downloading resource from 'https://downloads.mesosphere.com/java/jre-8u144-linux-x64.tar.gz' to '/var/lib/mesos/slave/slaves/ad94e382-26c1-4832-bbff-b08e21a835d6-S8/frameworks/ad94e382-26c1-4832-bbff-b08e21a835d6-0001/executors/kubernetes.151a7920-b3ad-11e7-963f-46f4cd883ac6/runs/c581bf73-06f9-4fec-9841-c2f798ede98e/jre-8u144-linux-x64.tar.gz'
I1018 02:36:06.646978  4305 fetcher.cpp:123] Extracted '/var/lib/mesos/slave/slaves/ad94e382-26c1-4832-bbff-b08e21a835d6-S8/frameworks/ad94e382-26c1-4832-bbff-b08e21a835d6-0001/executors/kubernetes.151a7920-b3ad-11e7-963f-46f4cd883ac6/runs/c581bf73-06f9-4fec-9841-c2f798ede98e/jre-8u144-linux-x64.tar.gz' into '/var/lib/mesos/slave/slaves/ad94e382-26c1-4832-bbff-b08e21a835d6-S8/frameworks/ad94e382-26c1-4832-bbff-b08e21a835d6-0001/executors/kubernetes.151a7920-b3ad-11e7-963f-46f4cd883ac6/runs/c581bf73-06f9-4fec-9841-c2f798ede98e'
I1018 02:36:06.647064  4305 fetcher.cpp:582] Fetched 'https://downloads.mesosphere.com/java/jre-8u144-linux-x64.tar.gz' to '/var/lib/mesos/slave/slaves/ad94e382-26c1-4832-bbff-b08e21a835d6-S8/frameworks/ad94e382-26c1-4832-bbff-b08e21a835d6-0001/executors/kubernetes.151a7920-b3ad-11e7-963f-46f4cd883ac6/runs/c581bf73-06f9-4fec-9841-c2f798ede98e/jre-8u144-linux-x64.tar.gz'
I1018 02:36:06.647080  4305 fetcher.cpp:444] Fetching URI 'https://downloads.mesosphere.com/kubernetes/assets/0.2.2-1.7.7-beta/kubernetes-scheduler.zip'
I1018 02:36:06.647092  4305 fetcher.cpp:285] Fetching directly into the sandbox directory
I1018 02:36:06.647117  4305 fetcher.cpp:222] Fetching URI 'https://downloads.mesosphere.com/kubernetes/assets/0.2.2-1.7.7-beta/kubernetes-scheduler.zip'
I1018 02:36:06.647133  4305 fetcher.cpp:165] Downloading resource from 'https://downloads.mesosphere.com/kubernetes/assets/0.2.2-1.7.7-beta/kubernetes-scheduler.zip' to '/var/lib/mesos/slave/slaves/ad94e382-26c1-4832-bbff-b08e21a835d6-S8/frameworks/ad94e382-26c1-4832-bbff-b08e21a835d6-0001/executors/kubernetes.151a7920-b3ad-11e7-963f-46f4cd883ac6/runs/c581bf73-06f9-4fec-9841-c2f798ede98e/kubernetes-scheduler.zip'
I1018 02:36:07.951107  4305 fetcher.cpp:123] Extracted '/var/lib/mesos/slave/slaves/ad94e382-26c1-4832-bbff-b08e21a835d6-S8/frameworks/ad94e382-26c1-4832-bbff-b08e21a835d6-0001/executors/kubernetes.151a7920-b3ad-11e7-963f-46f4cd883ac6/runs/c581bf73-06f9-4fec-9841-c2f798ede98e/kubernetes-scheduler.zip' into '/var/lib/mesos/slave/slaves/ad94e382-26c1-4832-bbff-b08e21a835d6-S8/frameworks/ad94e382-26c1-4832-bbff-b08e21a835d6-0001/executors/kubernetes.151a7920-b3ad-11e7-963f-46f4cd883ac6/runs/c581bf73-06f9-4fec-9841-c2f798ede98e'
I1018 02:36:07.951207  4305 fetcher.cpp:582] Fetched 'https://downloads.mesosphere.com/kubernetes/assets/0.2.2-1.7.7-beta/kubernetes-scheduler.zip' to '/var/lib/mesos/slave/slaves/ad94e382-26c1-4832-bbff-b08e21a835d6-S8/frameworks/ad94e382-26c1-4832-bbff-b08e21a835d6-0001/executors/kubernetes.151a7920-b3ad-11e7-963f-46f4cd883ac6/runs/c581bf73-06f9-4fec-9841-c2f798ede98e/kubernetes-scheduler.zip'
I1018 02:36:07.951246  4305 fetcher.cpp:444] Fetching URI 'https://downloads.mesosphere.io/libmesos-bundle/libmesos-bundle-1.10-1.4-63e0814.tar.gz'
I1018 02:36:07.951257  4305 fetcher.cpp:285] Fetching directly into the sandbox directory
I1018 02:36:07.951284  4305 fetcher.cpp:222] Fetching URI 'https://downloads.mesosphere.io/libmesos-bundle/libmesos-bundle-1.10-1.4-63e0814.tar.gz'
I1018 02:36:07.951303  4305 fetcher.cpp:165] Downloading resource from 'https://downloads.mesosphere.io/libmesos-bundle/libmesos-bundle-1.10-1.4-63e0814.tar.gz' to '/var/lib/mesos/slave/slaves/ad94e382-26c1-4832-bbff-b08e21a835d6-S8/frameworks/ad94e382-26c1-4832-bbff-b08e21a835d6-0001/executors/kubernetes.151a7920-b3ad-11e7-963f-46f4cd883ac6/runs/c581bf73-06f9-4fec-9841-c2f798ede98e/libmesos-bundle-1.10-1.4-63e0814.tar.gz'
I1018 02:36:10.059612  4305 fetcher.cpp:123] Extracted '/var/lib/mesos/slave/slaves/ad94e382-26c1-4832-bbff-b08e21a835d6-S8/frameworks/ad94e382-26c1-4832-bbff-b08e21a835d6-0001/executors/kubernetes.151a7920-b3ad-11e7-963f-46f4cd883ac6/runs/c581bf73-06f9-4fec-9841-c2f798ede98e/libmesos-bundle-1.10-1.4-63e0814.tar.gz' into '/var/lib/mesos/slave/slaves/ad94e382-26c1-4832-bbff-b08e21a835d6-S8/frameworks/ad94e382-26c1-4832-bbff-b08e21a835d6-0001/executors/kubernetes.151a7920-b3ad-11e7-963f-46f4cd883ac6/runs/c581bf73-06f9-4fec-9841-c2f798ede98e'
I1018 02:36:10.059685  4305 fetcher.cpp:582] Fetched 'https://downloads.mesosphere.io/libmesos-bundle/libmesos-bundle-1.10-1.4-63e0814.tar.gz' to '/var/lib/mesos/slave/slaves/ad94e382-26c1-4832-bbff-b08e21a835d6-S8/frameworks/ad94e382-26c1-4832-bbff-b08e21a835d6-0001/executors/kubernetes.151a7920-b3ad-11e7-963f-46f4cd883ac6/runs/c581bf73-06f9-4fec-9841-c2f798ede98e/libmesos-bundle-1.10-1.4-63e0814.tar.gz'
I1018 02:36:10.437222     4 exec.cpp:162] Version: 1.4.0
I1018 02:36:10.441067    12 exec.cpp:237] Executor registered on agent ad94e382-26c1-4832-bbff-b08e21a835d6-S8
I1018 02:36:10.451203     7 executor.cpp:171] Received SUBSCRIBED event
I1018 02:36:10.451658     7 executor.cpp:175] Subscribed executor on 10.0.2.82
I1018 02:36:10.451961     7 executor.cpp:171] Received LAUNCH event
I1018 02:36:10.452438     7 executor.cpp:633] Starting task kubernetes.151a7920-b3ad-11e7-963f-46f4cd883ac6
I1018 02:36:10.457615     7 executor.cpp:477] Running '/opt/mesosphere/active/mesos/libexec/mesos/mesos-containerizer launch <POSSIBLY-SENSITIVE-DATA>'
I1018 02:36:10.461586     7 executor.cpp:646] Forked command at 14
I1018 02:36:21.698930     5 executor.cpp:925] Command exited with status 11 (pid: 14)
I1018 02:36:22.700939    13 process.cpp:1072] Failed to accept socket: future discarded

**Comment by adam-carbone** [comment]
INFO  2017-10-18 03:06:29,651 [main] com.mesosphere.sdk.dcos.DcosCertInstaller:determineCertPath(87): Cert file not found at the expected path, /var/lib/mesos/slave/slaves/ad94e382-26c1-4832-bbff-b08e21a835d6-S9/frameworks/ad94e382-26c1-4832-bbff-b08e21a835d6-0001/executors/kubernetes.4c316c03-b3b1-11e7-963f-46f4cd883ac6/runs/1bd10563-0f93-4337-9bd8-9b8945774bdf/.ssl/ca-bundle.crt, for a 1.10 cluster, checking the pre 1.10 path.
INFO  2017-10-18 03:06:29,652 [main] com.mesosphere.sdk.dcos.DcosCertInstaller:determineCertPath(92): Cert file not found at the expected path, /var/lib/mesos/slave/slaves/ad94e382-26c1-4832-bbff-b08e21a835d6-S9/frameworks/ad94e382-26c1-4832-bbff-b08e21a835d6-0001/executors/kubernetes.4c316c03-b3b1-11e7-963f-46f4cd883ac6/runs/1bd10563-0f93-4337-9bd8-9b8945774bdf/.ssl/ca.crt, for a pre 1.10 cluster.
INFO  2017-10-18 03:06:29,652 [main] com.mesosphere.sdk.dcos.DcosCertInstaller:installCertificate(51): Cert file not found in the sandbox. This is expected if the cluster is not in STRICTmode. No work to be done.
ERROR 2017-10-18 03:06:30,325 [main] com.mesosphere.sdk.specification.DefaultService:initService(131): Service has been previously told to uninstall, this cannot be reversed. Reenable the uninstall flag to complete the process.

**Comment by pires** [comment]
This is a DC/OS bug that is supposedly fixed in 1.10.1. Can you please retry and re-open if it still doesn't work?

**Comment by sm0nt** [comment]
I had this same issue, even after upgrading to 1.10.1.  I was able to get Kubernetes to install by going to the Exhibitor for Zookeeper page and deleting the "dcos-service-kubernetes" folder in the Explorer tab.  After doing that Kubernetes installed for me.

**Comment by pires** [comment]
cc @spahl please help. don't know for sure what to do here.

**Comment by rimusz** [comment]
seen this issue a few times on 1.10.2 too

**Comment by pires** [comment]
Hello all, are you still observing this with the latest version of the package and more recent DC/OS 1.10.x?

**Comment by josepedro** [comment]
I had these problems and I got follow steps from this link: https://docs.mesosphere.com/1.8/usage/managing-services/uninstall/

**Comment by cbakersdl** [comment]
I had this same problem but with Grafana on version 1.11.5. The solution was as @sm0nt suggested, delete it from exhibitor. 
I had trouble finding the URI at first so posting here for posterity:
http://<my-dcos-master>:8181/exhibitor/v1/ui/index.html
