### ISSUE TITLE
cannot get 3 nodes

### ISSUE THREAD

**Issue by errordeveloper** [mesosphere/dcos-kubernetes-quickstart#31]
I've deployed DC/OS using CloudFormation with all default parameter values.

First time I installed Kubernetes (with default config), I only got 1 node and 14h later it was still only one of them:
```
> kubectl -s localhost:9000 get nodes
NAME                                   STATUS    AGE       VERSION
kube-node-0-kubelet.kubernetes.mesos   Ready     14h       v1.7.7
```

I've re-deployed it on the same cluster, and got 2 nodes:
```
> kubectl -s localhost:9000 get nodes
NAME                                   STATUS    AGE       VERSION
kube-node-0-kubelet.kubernetes.mesos   Ready     6m        v1.7.7
kube-node-2-kubelet.kubernetes.mesos   Ready     6m        v1.7.7
```

**Comment by hectorj2f** [comment]
@errordeveloper Thanks for opening this issue. Could you share the logs you get with `dcos service log --lines=N kubernetes`, and also `dcos task --completed` ? That'll help us to understand what is the problem.

**Comment by errordeveloper** [comment]
@hectorj2f please take a look at https://gist.github.com/errordeveloper/7d976e17c7a25e59d1d6058854a6a67a.

**Comment by hectorj2f** [comment]
@errordeveloper The problem is due to insufficient resources to schedule all the Kubernetes components. For instance, I can see this warning in the dcos logs `Unable to find any offers which fulfill requirement provided by step kube-node-1:[kube-proxy, kubelet]: kube-node-1:[kube-proxy, kubelet]`. 

Please, have a look at the docs here: https://github.com/mesosphere/dcos-kubernetes/blob/master/docs/package/install.md

**Comment by errordeveloper** [comment]
@hectorj2f oh, I suspected that.. it's too bad, cause I thought 5 slave instances should be sufficient to run 3 Kubernetes nodes.

**Comment by errordeveloper** [comment]
I've had `weavescope` and `weavescope-probe` packages installed, after removing those I can see 3 nodes. I'm still not convinced Kubernetes on DC/OS should require so much resources.

**Comment by hectorj2f** [comment]
@errordeveloper Sure, I understand. However, the idea is to have some default settings (with HA, ...) where you can actually run stuff. 

For a playground environment, I suggest you to change the settings  of the `options.json` file such as reducing the amount of kube-nodes, control-plane replicas, memory and cpu requirements, as mentioned in https://docs.mesosphere.com/service-docs/beta-kubernetes/0.2.2-1.7.7-beta/install/.

**Comment by pires** [comment]
@errordeveloper the defaults are meant for a trivially good overall UX when installing Kubernetes on DC/OS for the first time. As we speak, there are no plans to make this less resource demanding for the purpose of just trying it out on less DC/OS private agents or much less resources.

Thank you for reporting.

**Comment by pires** [comment]
@errordeveloper with [0.6.1-1.9.3-beta](https://github.com/mesosphere/dcos-kubernetes-quickstart/pull/64) merged, it should be easier for you (or anyone else with limited resources) to try this out :)
