### ISSUE TITLE
Accessing a Service from outside the cluster

### ISSUE THREAD

**Issue by vishal-biyani** [mesosphere/dcos-kubernetes-quickstart#36]
I have deployed kubernetes cluster using `make deploy` command mentioned in README.md.
Nginx is deployed on top this cluster and exposed using `NodePort` service. If I try to hit the nodeIP:nodePort I get `connection refused` error.

I can see service is listening on nodePort.
```
netstat -tulpn | grep 30302
tcp6       0      0 :::30302                :::*                    LISTEN      7168/./kube-proxy 
```

Hitting the endpoint from same machine results in same error.
```
curl -v http://localhost:30302
* Rebuilt URL to: http://localhost:30302/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* connect to 127.0.0.1 port 30302 failed: Connection refused
* Failed to connect to localhost port 30302: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 30302: Connection refuse
```

Creating service of type 'LoadBalancer' remains in pending state. 
What is the right way to access deployed kubernetes workloads outside the cluster ? Are there any additional steps required apart from creating a kubernetes service?

**Comment by smugcloud** [comment]
Hi @vishal-biyani,

For your nginx container, can you share details on the Kubernetes manifests, and image you used?  It looks like kube-proxy is routing the traffic, but perhaps your nginx container is listening on a different port than what you have specified.

For your `LoadBalancer` question, we have not enabled the `cloud-provider` flags on Kubernetes yet (this is coming shortly), so an external load balancer will not be configured.

At this time, the best way to expose a Kubernetes application is to use the `NodePort`.  We have an example here: https://github.com/mesosphere/dcos-kubernetes-quickstart/blob/master/examples/os-detector/os-detector.md

**Comment by rimusz** [comment]
hey @vishal-biyani I have made a demo hoe to expose your web apps externally https://github.com/rimusz/dcos-k8s-beer-demo 
Check from https://github.com/rimusz/dcos-k8s-beer-demo#helm-setup part

**Comment by pires** [comment]
@smugcloud can you please add documentation to our public docs about how a user can access a `Service` from outside of the cluster? Ping me and let's sync because while I have all the possible solutions on my mind, time is really short for me.

**Comment by smugcloud** [comment]
Hi @vishal-biyani, we have updated documentation that walks through exposing services.  Currently, we support the AWS `cloud-provider` (configuration flag at Kubernetes package installation), or an [Ingress resource](https://docs.mesosphere.com/services/beta-kubernetes/0.4.0-1.9.0-beta/ingress/).

Let me know if you run into any issues.

**Comment by nadendlaprasad** [comment]
Is it possible to expose nodeport service via marathon-lb ? If yes , can you please provide a link which can help me understand, how a nodeport service can be exposed via marathon-lb ?
