### ISSUE TITLE
Invalid SSH key format error on GCE dashboard

### ISSUE THREAD

**Issue by vishal-biyani** [mesosphere/dcos-kubernetes-quickstart#37]
I have created DCOS+Kubernetes cluster on GCE using procedure mentioned in README.md.
When I try to edit any parameters (Network tags etc.) for VMs spawned by above procedure, GCE dashboard does not allow to save any changes since the SSH public key already injected does not follow standard SSH key format. GCE dashboard shows bellow error:

```
Invalid key. Required format: <protocol> <key-blob> <username@example.com> or <protocol> <key-blob> google-ssh {"userName":"<username@example.com>","expireOn":"<date>"}
```

This makes doing any changes to VM configuration from GCE dashboard impossible.

**Comment by pires** [comment]
@spahl what can be done here?

**Comment by pires** [comment]
@rimusz @hectorj2f  any hints?

**Comment by pires** [comment]
@vishal-biyani can you try the latest version of the package and instructions, which now use Terraform instead of dcos-launch, please?

**Comment by pires** [comment]
@rimusz can you please help identify this issue?

**Comment by vishal-biyani** [comment]
@pires Thanks for reverting but I am not active on the project and don't have the setup readily available with me anymore. I will see if I can spend some time and quickly spin and test this out.

**Comment by pires** [comment]
@vishal-biyani I will then close this issue. Please, if you ever face this issue again, don't hesitate and comment here, and I'll re-open it. Thank you for reporting!
