### ISSUE TITLE
Unable to deploy with local universe. 

### ISSUE THREAD

**Issue by rezblaze** [mesosphere/dcos-kubernetes-quickstart#44]
cd /root
git clone https://github.com/mesosphere/universe.git --branch version-3.x
cd universe/docker/local-universe/
sudo make base
sudo make DCOS_VERSION=1.10 DCOS_PACKAGE_INCLUDE="beta-kubernetes:0.3.0-1.7.10-beta" local-universe

Fails with:

Successfully built xxxx
Errors: ['beta-kubernetes']
These packages are not included in the image.

**Comment by mjschmidt** [comment]
If you look at the resource file for the beta-kubernetes did you make sure to 
1) bring all of those resources into what ever environment you plan on using them (since I am assuming you are doing a local universe you are not going to be in an online environment?
2) Re-point the resources in the resource file to the new location that those files are being held?

**Comment by mjschmidt** [comment]
That file would be in <local_universe_name>/repo/packages/B/beta-kubernetes/4 (or what ever version number you are currently trying to deploy)

**Comment by cap1981** [comment]
this is the error i see while running 
sudo make base
```
gpg: requesting key 7BD9BF62 from hkp server pgp.mit.edu
gpgkeys: key 573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62 can't be retrieved
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
```

**Comment by pires** [comment]
@spahl do we support local universe?

**Comment by mjschmidt** [comment]
I use to run it, honestly it is way easier to just run pure kubernetes. I ran into tons of issues with trying to run kubernetes ontop of DC/OS

**Comment by pires** [comment]
Would be great to get all those issues reported @mjschmidt. Unfortunately, just saying _tons of issues_ won't help us help you :(

**Comment by cap1981** [comment]
local universe seems to have everything but when deploying start out with FAILED etcd, stderr file doesn't have anything looks like error but stdout have last thing below.
```
 ######  Starting etcd -- etcd-1-peer ###### 
2018-02-08 14:57:03.321638 I | etcdmain: etcd Version: 3.2.9
2018-02-08 14:57:03.321791 I | etcdmain: Git SHA: f1d7dd8
2018-02-08 14:57:03.321796 I | etcdmain: Go Version: go1.8.4
2018-02-08 14:57:03.321799 I | etcdmain: Go OS/Arch: linux/amd64
2018-02-08 14:57:03.321804 I | etcdmain: setting maximum number of CPUs to 8, total number of available CPUs is 8
2018-02-08 14:57:03.321851 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2018-02-08 14:57:03.321872 I | embed: peerTLS: cert = etcd-crt.pem, key = etcd-key.pem, ca = , trusted-ca = ca-crt.pem, client-cert-auth = false
2018-02-08 14:57:03.322604 C | etcdmain: tls: private key does not match public key
```

eventuallly they start running and also spins up other component  goes all the way to deploying nodes but it fails there.

```
I0205 17:27:58.641865 18305 fetcher.cpp:285] Fetching directly into the sandbox directory
I0205 17:27:58.641959 18305 fetcher.cpp:222] Fetching URI 'http://api.kubernetes.marathon.l4lb.thisdcos.directory/v1/artifacts/template/d90939dd-afee-4649-b591-9783b29eaa3f/kube-node/kubelet/kubeconfig'
I0205 17:27:58.641991 18305 fetcher.cpp:165] Downloading resource from 'http://api.kubernetes.marathon.l4lb.thisdcos.directory/v1/artifacts/template/d90939dd-afee-4649-b591-9783b29eaa3f/kube-node/kubelet/kubeconfig' to '/var/lib/mesos/slave/slaves/b2d57ed4-9b96-4914-81a8-22d9a9ed1041-S1/frameworks/b2d57ed4-9b96-4914-81a8-22d9a9ed1041-0002/executors/kube-node__53722c07-486a-47f5-b52f-36365d6b2db2/runs/cc0375ef-2e31-4497-9fe5-f1019b68548c/containers/8065c7e3-edde-47ac-a134-79ce3491740f/config-templates/kubeconfig'
E0205 17:27:58.715638 18305 fetcher.cpp:579] EXIT with status 1: Failed to fetch 'http://api.kubernetes.marathon.l4lb.thisdcos.directory/v1/artifacts/template/d90939dd-afee-4649-b591-9783b29eaa3f/kube-node/kubelet/kubeconfig': Error downloading resource, received HTTP return code 404


```

**Comment by cap1981** [comment]
@spahl @pires 
so is local universe supported or not? if you could reply quick please that be greatly appreciated.
Thank you!

**Comment by pires** [comment]
I can't answer because I never used it. But I can say the Kubernetes team hasn't tried it as well so it's safe to assume it is not supported in GA.

**Comment by cap1981** [comment]
Thanks @pires !

**Comment by pires** [comment]
@cap1981 @rezblaze local universe support will land next week!
