### ISSUE TITLE
Creating with AWS

### ISSUE THREAD

**Issue by f0ster** [mesosphere/dcos-kubernetes-quickstart#46]
When I run `make docker` , I can see my AWS creds being passed in, but when I run `make deploy PLATFORM=aws` or `make launch-dcos PLATFORM=aws`, I get errors about GCE not being found.  Should this not be a dependency since I am trying to install on AWS?

**Comment by hectorj2f** [comment]
@f0ster I just deployed my cluster on AWS following these steps without getting any error. I didn't specify any GCE credentials, and consequently I didn't get any error about it.

```
make docker
export PLATFORM=aws
make deploy
```

Could you print the errors you're seeing ?

**Comment by rimusz** [comment]
me too followed the steps above, got set dc/os cluster on aws just fine
