### ISSUE TITLE
Error: 'tls: oversized record received with length 20527'

### ISSUE THREAD

**Issue by seanhig** [mesosphere/dcos-kubernetes-quickstart#55]
DC/OS 1.10 on CentOS7.4

Following these instructions:
https://docs.mesosphere.com/services/beta-kubernetes/0.4.0-1.9.0-beta/connecting-clients/

Everything works fine from the CLI, and http://localhost:9000 returns the expected list of apis...

But when I try to browse to:

`http://localhost:9000/ui`

I get:

```
Error: 'tls: oversized record received with length 20527'
Trying to reach: 'https://9.0.10.3:9090/'
```

If I change the url from https to http, it will bring up the dashboard:

localhost:9000/api/v1/namespaces/kube-system/services/__http__:kubernetes-dashboard:/proxy/#!/overview?namespace=default

But heapster graphs will not show.

I'm sure I had this working fine in an earlier try at beta-kubernetes without having to do anything.

I do see a lot of these in the logs:

`No $MESOS_SANDBOX/.ssl directory found. Cannot install certificate.
`
Not sure if it is related.

Would like to get this working properly... thanks.

**Comment by seanhig** [comment]
For anyone else experiencing this.. the heapster issue is not tied to the TLS.  After running:

`kubectl proxy
`
On top of the ssh tunnel they describe in the DC/OS Connecting Clients page, the url:

`localhost:8001/ui
`
Does load up the dashboard correctly, however __heapster__ graphs are still broken.
> Note that the original url works fine as well and `kubectl proxy` isn't really needed on top of the SSH tunnel. 

Looking at the __kubernetes-dashboard__ logs, there are issues connecting to heapster (likely timing of the scheduler install).

This illustrates the issue:

```
Creating in-cluster Heapster client
Could not enable metric client: Health check failed: an error on the server ("[-]healthz failed: could not get the latest data batch\nhealthz check failed") has prevented the request from succeeding (get services heapster). Continuing.
```

I'm new to k8s, and it appears there is no "restart" proper... but that is what is needed... so after digging through a few threads, it seemed killing it was the solution, and k8s would auto-restart it. So...

`kubectl delete pod --namespace=kube-system kubernetes-dashboard-blahblah-xyz
`
(where blahblah is the uuid for your pod)

Checking the logs when it comes back, it connects to heapster cleanly:

```
Creating in-cluster Heapster client
Successful initial request to heapster
```

And the graphs are now in the dashboard.

Probably as good as it is going to get for this beta ;)

**Comment by pires** [comment]
This will be simplified as soon as we remove the need for the SSH tunnel - which will require DC/OS 1.11

**Comment by pires** [comment]
Thank you for reporting @seanhig. Our next release will replace Heapster with metrics-server and you should stop seeing this issue.
