### ISSUE TITLE
Kubernetes on DC/OS general availability timeline

### ISSUE THREAD

**Issue by tedmiston** [mesosphere/dcos-kubernetes-quickstart#56]
Hi - I'm currently just getting started with the Kubernetes on DC/OS beta and was asked to reach out about what the timeline is for general availability.

I saw [the beta warning](https://github.com/mesosphere/dcos-kubernetes-quickstart/commit/a17f554c595428a7fbcfae017513a64ecc7dfc0b) added in September 2017 with DC/OS 1.10 and was curious if this status has changed since then.  Does GA come with the 1.11 release or before/after?

I searched the docs and [release policy](https://docs.mesosphere.com/1.10/release-notes/version-policy/) but didn't see this info out there yet.

@dmmcquay @pires It looks like one of you might be the best person to ask.

**Comment by pires** [comment]
Hi @tedmiston. We are currently working towards GA and it should be announced simultaneously with DC/OS 1.11. This should happen still in Q1.

We are planning to release yet another beta, followed by one or more release candidates until we hit GA. Join our community slack and be notified when that happens.

**Comment by tedmiston** [comment]
@pires Thank you! That sounds great.

I think this is the Slack team you mentioned - https://dcos-community.slack.com/.  I'm seeing:

> Don't have an @mesosphere.io or @mesosphere.com email address? 
Contact your Workspace Administrator for an invitation.

How does one join without an official email?

**Comment by smugcloud** [comment]
Hi @tedmiston try this link.  You can get an invite on your own:

http://chat.dcos.io/

**Comment by tedmiston** [comment]
thank you both.  looks like i'm in!
