### ISSUE TITLE
kube-dns crashes because it can't access Kubernetes API

### ISSUE THREAD

**Issue by pires** [mesosphere/dcos-kubernetes-quickstart#58]
@wyfligamo reported the following in #57:

(issue comments edited by @pires, in order to make things more clear here)

my kube-dns pod status is CrashLoopBackOff and kubedns container log says

```
[root@localhost ~]# kubectl get pods --all-namespaces 
NAMESPACE     NAME                        READY     STATUS             RESTARTS   AGE
kube-system   heapster-7d7b7f4f87-brp2l   1/1       Running            0          21h
kube-system   kube-dns-6dc79b7c4-dbw5g    1/3       CrashLoopBackOff   506        21h
```

My k8s only start kube-dns and heapster pods, is that right? **they can't communicate with api service, but I can get api response with browser outside the cluster**

```
[root@localhost ~]# kubectl logs --namespace=kube-system heapster-7d7b7f4f87-brp2l
E0202 05:26:09.524966       1 reflector.go:190] k8s.io/heapster/metrics/heapster.go:322: Failed to list *v1.Pod: Get https://kubernetes.default/api/v1/pods?resourceVersion=0: dial tcp: i/o timeout
```

```
[root@localhost ~]# kubectl logs --namespace=kube-system kube-dns-6dc79b7c4-dbw5g kubedns
E0202 05:23:47.244936       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:150: Failed to list *v1.Service: Get https://10.100.0.1:443/api/v1/services?resourceVersion=0: dial tcp 10.100.0.1:443: i/o timeout
E0202 05:23:47.244981       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:147: Failed to list *v1.Endpoints: Get https://10.100.0.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.100.0.1:443: i/o timeout
I0202 05:23:47.742922       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0202 05:23:48.242824       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0202 05:23:48.742850       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0202 05:23:49.242879       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
```

**Comment by pires** [comment]
@wyfligamo looking at your logs it seems that kube-dns can't connect to the Kubernetes API (`10.100.0.1`). Does your host network use any of `10.0.0.0/8` or `10.100.0.0/16` CIDRs?

You can reach the API from your browser because the SSH tunnel forwards to the DC/OS VIP `apiserver-insecure.kubernetes.l4lb.thisdcos.directory:9000` and not the Kubernetes API (internal to the Kubernetes cluster) Service, `kubernetes.default.svc.cluster.local`.

**Comment by wyfligamo** [comment]
@pires Thanks for follow my question.
My cluster IP is 10.100.100.11-17, is that a problem? Can I change the k8s service cluster IPs CIDR ?

**Comment by pires** [comment]
Yes, it's a problem. Yes, you can.

- Assuming you're installing with the default options, create a JSON file with the following contents:

  ```json
  {
    "kubernetes": {
      "service_cidr": "<YOUR_CIDR_HERE>"
    },
  }
  ```

  **Attention:** replace `<YOUR_CIDR_HERE>` above with a CIDR block that is not assigned anywhere 
  else, e.g. `10.90.0.0/16`.

- Save the file.
- Uninstall the framework and wait for all tasks to go away.
- Install the framework as follows:
  ```shell
  dcos package install --yes beta-kubernetes --options=<JSON_FILEPATH>
  ```

  **Attention**: replace `<JSON_FILEPATH>` above with the path to the JSON file you created above.

**Comment by pires** [comment]
I will add a sub-section describing this in our Advanced Installation package docs.

**Comment by rimusz** [comment]
in the case of using this `quickstart`, `options.json` gets created in `.deploy` folder when you e.g. do `make gce`, then edit that file and add `service_cidr` there

**Comment by pires** [comment]
Thank you @rimusz.

**Comment by wyfligamo** [comment]
@pires Thanks, I'll have a try and feedback in next Monday.

**Comment by wyfligamo** [comment]
Hi, @pires 
I change my service CIDR to 10.90.0.0/16, and I'm sure that IPs are not in use, but still get the same problem

**Comment by wyfligamo** [comment]
@pires , I make a mistake, the error is not same, 
<pre>
E0205 11:18:05.352816       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:150: Failed to list *v1.Service: Get https://10.90.0.1:443/api/v1/services?resourceVersion=0: x509: certificate is valid for 127.0.0.1, 10.100.0.1, not 10.90.0.1
E0205 11:18:05.419043       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:147: Failed to list *v1.Endpoints: Get https://10.90.0.1:443/api/v1/endpoints?resourceVersion=0: x509: certificate is valid for 127.0.0.1, 10.100.0.1, not 10.90.0.1
</pre>
It seems  like I need a certificate for new CIDR?

**Comment by pires** [comment]
@wyfligamo correct. This is a bug on our end and I have no workaround for you at this point. We will be releasing a new beta later this week and a fix will be included. Please, bear with us.

Thank you for your feedback!

**Comment by wyfligamo** [comment]
@pires That's OK, wish you success :  )
