### ISSUE TITLE
Internet via proxy

### ISSUE THREAD

**Issue by ezreal92170** [mesosphere/dcos-kubernetes-quickstart#7]
I run DCOS on coreOS and i just try Beta-Kubernetes on DCOS 1.10.0
I use proxy to connect to Internet.

All the tasks are in a running state, but when i try to install a new pod i get the following error

 createPodSandbox for pod "redis-master-1405623842-zt2hq_default(97f75286-972a-11e7-937b-e41f13303b18)" failed: rpc error: code = 2 desc = unable to pull sandbox image 
"gcr.io/google_containers/pause-amd64:3.0": Error response from daemon: {"message":"Get https://gcr.io/v1/_ping: dial tcp 74.125.133.82:443: i/o timeout"}

I tried to pull gcr.io/google_containers/pause-amd64:3.0 from command line on my coreos host and it works.

Can we use this framework with a proxy to access Internet ?

**Comment by smugcloud** [comment]
Hi @ezreal92170, this sounds like a routing or firewall issue.  The proxy should not matter, as long as the `kubelet` container has a route to the Internet.  If you enter the container, can you ping the GCR IP?
```
nsenter -t <KUBELET PID> -m -n -p -w
```

**Comment by ezreal92170** [comment]
Just to clarify,  in my environment i don't have direct access to Internet. I can only use http and https protocol to access the internet and only through a "corporate" proxy.

In this error message

`Error response from daemon: {"message":"Get https://gcr.io/v1/_ping: dial tcp 74.125.133.82:443: i/o timeout"}`

we see that the daemon try direct connect to the Internet (ignoring my docker core os host configuration) because dns resolution happened. The direct connection will always fail in my environnement, i must to try to configure a http proxy for the daemon

**Comment by spahl** [comment]
Thanks for the details. We are currently in the process of "air gapping" the framework. It will be runnable behind the firewall soon.

**Comment by ezreal92170** [comment]
Thanks, if you have some clue to modify inside container any configuration before a new released i can do some test.

**Comment by pires** [comment]
This will be fixed with a new release to happen next week.

**Comment by ezreal92170** [comment]
thx i will be happy to test that.

**Comment by pires** [comment]
Can you try [the new release](https://docs.mesosphere.com/service-docs/beta-kubernetes/0.2.0-1.7.6-beta) and report back?

**Comment by pires** [comment]
Closing. Please report back if you encounter any issues.
