### ISSUE TITLE
kubeconfig fails

### ISSUE THREAD

**Issue by daniel-sherwood** [mesosphere/dcos-kubernetes-quickstart#76]
Hi 

I have kubernetes-1.0.2-1.9.6 installed on a DC/OS 0.11 cluster.  The kubconfig command fails as follows...

```
[p3061@cuckoo-accessvm-p3061 ~]$ dcos kubernetes kubeconfig
failed to retrieve 'cluster.name'
```

Cheers

Daniel Sherwood

**Comment by pires** [comment]
@hectorj2f please help here.

**Comment by hectorj2f** [comment]
@daniel-sherwood This could happen when there isn't a cluster section in the `dcos.toml` configuration file of your cluster. Could you run `dcos auth login` to your cluster ? We need to be sure you're logged in the right cluster. 
Could you also print the content of your dcos.toml file e.g `~/.dcos/clusters/CLUSTER_ID/dcos.toml` ?

**Comment by daniel-sherwood** [comment]
Tried that - still not working.

```
[p3061@cuckoo-accessvm-p3061 ~]$ dcos auth login
If your browser didn't open, please go to the following link:

    http://192.168.208.100/login?redirect_uri=urn:ietf:wg:oauth:2.0:oob

Enter OpenID Connect ID Token: <TOKEN>
Login successful!
[p3061@cuckoo-accessvm-p3061 ~]$ dcos kubernetes kubeconfig
failed to retrieve 'cluster.name'
[p3061@cuckoo-accessvm-p3061 ~]$ cat ~/.dcos/clusters/e5bc27d5-da21-46ce-9f56-a45320ff2361/dcos.toml
[core]
dcos_url = "http://192.168.208.100"
dcos_acs_token = "<TOKEN>"
[p3061@cuckoo-accessvm-p3061 ~]$
```

**Comment by daniel-sherwood** [comment]
Remved ~/.dcos/ and re-ran 'dcos cluster setup' and it is now working.

Thanks.
