### ISSUE TITLE
Cloud Provider option makes kube-controller-manager to fail

### ISSUE THREAD

**Issue by davideberdin** [mesosphere/dcos-kubernetes-quickstart#79]
I am using the new version of Kubernetes 1.9.6 and I noticed that no matter what kind of configuration I use (even the default options), when enabling the **aws** cloud-provider the **kube-controller-manager** is unable to start. The error that is throwing is the following:

```
 ######  Starting Kube CONTROLLER MANAGER -- kube-controller-manager-0-instance ###### 
I0406 16:15:12.779558      10 controllermanager.go:108] Version: v1.9.6
I0406 16:15:12.786006      10 leaderelection.go:174] attempting to acquire leader lease...
I0406 16:15:12.871094      10 leaderelection.go:184] successfully acquired lease kube-system/kube-controller-manager
I0406 16:15:12.871316      10 event.go:218] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"kube-system", Name:"kube-controller-manager", UID:"f275b8cf-39ab-11e8-9288-028a57b514c0", APIVersion:"v1", ResourceVersion:"7486", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' ip-10-0-1-211.eu-central-1.compute.internal became leader
I0406 16:15:12.893967      10 aws.go:1000] Building AWS cloudprovider
I0406 16:15:12.894005      10 aws.go:963] Zone not specified in configuration file; querying AWS metadata service
E0406 16:15:13.071847      10 tags.go:94] Tag "KubernetesCluster" nor "kubernetes.io/cluster/..." not found; Kubernetes may behave unexpectedly.
W0406 16:15:13.071873      10 tags.go:78] AWS cloud - no clusterID filtering applied for shared resources; do not run multiple clusters in this AZ.
F0406 16:15:13.071930      10 controllermanager.go:150] error building controller context: no ClusterID Found.  A ClusterID is required for the cloud provider to function properly.  This check can be bypassed by setting the allow-untagged-cloud option
```

If I disable the option, Kubernetes is able to run correctly again. 
It's worth to mention that I tried to install Kubernetes with the cloud-provider set on aws after a brand new DC/OS installation. Still though, the result was negative.
This is a **major issue** because I need to let Traefik to expose a Loadbalancer so that I can connect my services.

**Comment by bmcstdio** [comment]
@davideberdin Have you followed the [cloud-provider instructions](https://docs.mesosphere.com/services/kubernetes/1.0.2-1.9.6/advanced-install/#iam-policy-and-tag)? The following message suggests you don't have the required tag:

```
E0406 16:15:13.071847      10 tags.go:94] Tag "KubernetesCluster" nor "kubernetes.io/cluster/..." not found; Kubernetes may behave unexpectedly.
```

How did you create your DC/OS cluster?

**Comment by davideberdin** [comment]
You are right! I was totally missing the Tag "KubernetesCluster" in my CloudFormation. Thank you very much. I will close the issue :)
